image: golang:1.13-alpine

stages:
  - test
  - build

before_script:
  - apk add --no-cache make git gcc libc-dev
  - mkdir -p /go/src/github.com/yannh
  - cp -r $CI_PROJECT_DIR /go/src/github.com/jonyhy96/redis-dump-go
  - cd /go/src/github.com/jonyhy96/redis-dump-go

test:
  stage: test
  script:
  - make test

build:
  stage: build
  script:
  - make build
  - cp redis-dump-go ${CI_PROJECT_DIR}/
  artifacts:
    name: "$CI_PROJECT_NAME"
    paths:
    - redis-dump-go
    - LICENSE.txt
    when: on_success
